# Generated by Django 3.2.8 on 2021-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211026_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.IntegerField(choices=[(1, 'up'), (2, 'down')]),
        ),
    ]
